<?php
return array(
	'MMP\API'                 => 'classes/api.php',
	'MMP\Compatibility'       => 'classes/compatibility.php',
	'MMP\Dashboard'           => 'classes/dashboard.php',
	'MMP\Download'            => 'classes/download.php',
	'MMP\DB'                  => 'classes/db.php',
	'MMP\Resources'           => 'classes/resources.php',
	'MMP\Export'              => 'classes/export.php',
	'MMP\Fullscreen'          => 'classes/fullscreen.php',
	'MMP\Geo_Sitemap'         => 'classes/geo-sitemap.php',
	'MMP\Geocoding'           => 'classes/geocoding.php',
	'MMP\Google_Places'       => 'classes/google-places.php',
	'MMP\L10n'                => 'classes/l10n.php',
	'MMP\Map'                 => 'classes/map.php',
	'MMP\Maps_Marker_Pro'     => 'classes/maps-marker-pro.php',
	'MMP\Menu_License'        => 'classes/menu-license.php',
	'MMP\Menu_Map'            => 'classes/menu-map.php',
	'MMP\Menu_Maps'           => 'classes/menu-maps.php',
	'MMP\Menu_Marker'         => 'classes/menu-marker.php',
	'MMP\Menu_Markers'        => 'classes/menu-markers.php',
	'MMP\Menu_Settings'       => 'classes/menu-settings.php',
	'MMP\Menu_Support'        => 'classes/menu-support.php',
	'MMP\Menu_Tools'          => 'classes/menu-tools.php',
	'MMP\Menu'                => 'classes/menu.php',
	'MMP\Menus'               => 'classes/menus.php',
	'MMP\Migration'           => 'classes/migration.php',
	'MMP\Notice'              => 'classes/notice.php',
	'MMP\Settings'            => 'classes/settings.php',
	'MMP\Setup'               => 'classes/setup.php',
	'MMP\Shortcodes'          => 'classes/shortcodes.php',
	'MMP\SPBAS'               => 'classes/spbas.php',
	'MMP\TinyMCE'             => 'classes/tinymce.php',
	'MMP\Update'              => 'classes/update.php',
	'MMP\Upload'              => 'classes/upload.php',
	'MMP\Widget_Shortcode'    => 'classes/widget-shortcode.php'
);
