<?php
namespace MMP;

class Geo_Sitemap {
	/**
	 * Registers the hooks
	 *
	 * @since 4.0
	 */
	public function init() {
		if (Maps_Marker_Pro::$settings['sitemapGoogle']) {
			add_action('sm_buildmap', array($this, 'add_kml_to_google_sitemap'));
		}
		if (Maps_Marker_Pro::$settings['sitemapYoast']) {
			add_filter('wpseo_sitemap_index', array($this, 'add_sitemap_to_yoast'));
		}
	}

	/**
	 * Adds the KML links for maps to the sitemap generated by the Google XML Sitemaps plugin
	 *
	 * @since 4.0
	 */
	public function add_kml_to_google_sitemap() {
		$db = Maps_Marker_Pro::get_instance('MMP\DB');
		$api = Maps_Marker_Pro::get_instance('MMP\API');

		if (!class_exists('GoogleSitemapGenerator')) {
			return;
		}

		$sitemap = \GoogleSitemapGenerator::GetInstance();

		$maps = $db->get_all_maps(false, array(
			'include' => Maps_Marker_Pro::$settings['sitemapGoogleInclude'],
			'exclude' => Maps_Marker_Pro::$settings['sitemapGoogleExclude']
		));
		foreach ($maps as $map) {
			$sitemap->AddUrl(
				$api->link("/export/kml/{$map->id}/"),
				$map->updated_on,
				Maps_Marker_Pro::$settings['sitemapGoogleFrequency'],
				Maps_Marker_Pro::$settings['sitemapGooglePriority']
			);
		}
	}

	/**
	 * Adds the geo sitemap to the yoast sitemap index
	 *
	 * @since 4.0
	 */
	function add_sitemap_to_yoast() {
		$db = Maps_Marker_Pro::get_instance('MMP\DB');
		$api = Maps_Marker_Pro::get_instance('MMP\API');

		$maps = $db->get_all_maps(array(
			'orderby' => 'id',
			'sortorder' => 'DESC',
			'limit' => 1
		));
		if (!count($maps)) {
			return '';
		}

		$loc = $api->link('/geo-sitemap/');
		$lastmod = gmdate('c', strtotime($maps[0]->created_on));

		return "<sitemap><loc>{$loc}</loc><lastmod>{$lastmod}</lastmod></sitemap>";
	}

	/**
	 * Shows a geo sitemap with the links to fullscreen maps
	 *
	 * @since 4.0
	 */
	public function show_sitemap() {
		$db = Maps_Marker_Pro::get_instance('MMP\DB');
		$api = Maps_Marker_Pro::get_instance('MMP\API');

		$maps = $db->get_all_maps();

		$sitemap = new \SimpleXMLElement(
			'<?xml version="1.0" encoding="UTF-8"?>'
			. '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>'
		);
		foreach ($maps as $map) {
			$url = $sitemap->addChild('url');
			$url->addChild('loc', $api->link("/fullscreen/{$map->id}/"));
			$url->addChild('lastmod', date("Y-m-d", strtotime($map->updated_on)));
		}

		header('Access-Control-Allow-Origin: *');
		header('Cache-Control: no-cache, must-revalidate');
		header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
		header('Content-type: text/xml; charset=utf-8');

		echo $sitemap->asXML();
	}
}
